# Blog settings
permalink: /blog/:title


# My variables
name: Softwave
description: I code things.
google_verification: null


# File management
include: [".htaccess"]
#exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
